### ISSUE TITLE
Question/RFE

### ISSUE THREAD

**Issue by DALDEI** [cobbzilla/s3s3mirror#58]
I ran across this after aws-s3-mount lead to s3-bucketloader lead to here.
I like that this explicilty mentions checking ETags.

Questions:
1)  Are multi-part ETag comparisons attempted? 
--> I know this is only possible if you know the block size of the original transfer
--> Have you considered storing something like the cannonical ETag or a SHA1 as metadata?

2) Is User Metatadata copied aka "PUT COPY" ? or is it lost ?

3) Is there versioning support ? I.e. if Bucket1/File1 has 3 versions are they all copied or just the lastest?
4) Have you compared this to the recent cross-region bucket copy feature of AWS ?
--> Great feature but only works on newly created files and cross region.

**Comment by cobbzilla** [comment]
Hi @DALDEI thanks for your interest in s3s3mirror!

1) No, currently we only check ETag for the whole object. It would be conceivable to store metadata about the transfer on the destination, and for `KeyCopyJob` to check for this metadata and change its copying behavior based on it. For example, if metadata indicates the previous transfer was done via multi-part, we could find the chunk size used (stored in metadata), and then check each chunk's ETag (stored in metadata) to determine if any chunks need to be copied. This would increase the metadata storage overhead by a little bit, but could dramatically improve transfer speeds when there are a large number of very large objects.

I have considered storing a canonical SHA in the destination metadata, since this also would help the "copy to/from local storage" use case (supported on the `2.0-stable` branch). We cannot determine the ETag for local files, but we could compute the SHA sum. This would make copying to/from local storage more efficient and reliable.

2) I haven't worked much with UserMetadata. We retrieve the source metadata with `getObjectMetadata` in `KeyJob` and store it at the destination with `setNewObjectMetadata` as part of a `CopyObjectRequest`. If User Metadata is stored separately from what is returned by `getObjectMetadata`, then no, we would not copy that to the destination.

3) Only "full" S3 objects are copied, referenced by a unique S3 key. If the object versions are stored "with" the S3 object (under the same key), then I presume they would also be copied along with the object. If the versions each have a unique S3 key, then they would be copied if any only if their keys match the source key selection criteria (by ctime, pattern, etc). This is a bit of speculation, one could easily verify this behavior with a test copy of a versioned object.

4) No, I have not done this comparison. In addition to copying across regions, s3s3mirror also supports copying across AWS accounts (via `-C` / `--cross-account-copy` flag).
